version: '3.4'

services:
  zookeeper:
    image: "wurstmeister/zookeeper"
    ports: 
      - "2181:2181"
    
  kafka:
    image: 'wurstmeister/kafka:latest'
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka-producer:
    image: ${DOCKER_REGISTRY-}kafka-producer
    container_name: kafka-producer
    build:
      context: .
      dockerfile: KafkaProducer/Dockerfile
    environment:
      DONTNET_ENVIRONMENT: Development
    depends_on:
      - kafka
      - zookeeper

  kafka-consumer:
    image: ${DOCKER_REGISTRY-}kafka-consumer
    container_name: kafka-consumer
    build:
      context: .
      dockerfile: KafkaConsumer/Dockerfile
    environment:
      DONTNET_ENVIRONMENT: Development
    depends_on:
      - kafka
      - zookeeper
      - kafka-producer
